/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTrendsRouteImport } from './routes/_shell.trends'
import { Route as ShellTeacherRouteImport } from './routes/_shell.teacher'
import { Route as ShellStartRouteImport } from './routes/_shell.start'
import { Route as ShellSessionsRouteImport } from './routes/_shell.sessions'
import { Route as ShellProctorRouteImport } from './routes/_shell.proctor'
import { Route as ShellMeRouteImport } from './routes/_shell.me'
import { Route as ShellManagementRouteImport } from './routes/_shell.management'
import { Route as ShellEnrollmentRouteImport } from './routes/_shell.enrollment'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTrendsRoute = ShellTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeacherRoute = ShellTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStartRoute = ShellStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsRoute = ShellSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProctorRoute = ShellProctorRouteImport.update({
  id: '/proctor',
  path: '/proctor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeRoute = ShellMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ShellRoute,
} as any)
const ShellManagementRoute = ShellManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEnrollmentRoute = ShellEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof ShellAdminRoute
  '/enrollment': typeof ShellEnrollmentRoute
  '/management': typeof ShellManagementRoute
  '/me': typeof ShellMeRoute
  '/proctor': typeof ShellProctorRoute
  '/sessions': typeof ShellSessionsRoute
  '/start': typeof ShellStartRoute
  '/teacher': typeof ShellTeacherRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof ShellAdminRoute
  '/enrollment': typeof ShellEnrollmentRoute
  '/management': typeof ShellManagementRoute
  '/me': typeof ShellMeRoute
  '/proctor': typeof ShellProctorRoute
  '/sessions': typeof ShellSessionsRoute
  '/start': typeof ShellStartRoute
  '/teacher': typeof ShellTeacherRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/capture': typeof CaptureRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/enrollment': typeof ShellEnrollmentRoute
  '/_shell/management': typeof ShellManagementRoute
  '/_shell/me': typeof ShellMeRoute
  '/_shell/proctor': typeof ShellProctorRoute
  '/_shell/sessions': typeof ShellSessionsRoute
  '/_shell/start': typeof ShellStartRoute
  '/_shell/teacher': typeof ShellTeacherRoute
  '/_shell/trends': typeof ShellTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/landing'
    | '/login'
    | '/verify'
    | '/admin'
    | '/enrollment'
    | '/management'
    | '/me'
    | '/proctor'
    | '/sessions'
    | '/start'
    | '/teacher'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/landing'
    | '/login'
    | '/verify'
    | '/admin'
    | '/enrollment'
    | '/management'
    | '/me'
    | '/proctor'
    | '/sessions'
    | '/start'
    | '/teacher'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/capture'
    | '/landing'
    | '/login'
    | '/verify'
    | '/_shell/admin'
    | '/_shell/enrollment'
    | '/_shell/management'
    | '/_shell/me'
    | '/_shell/proctor'
    | '/_shell/sessions'
    | '/_shell/start'
    | '/_shell/teacher'
    | '/_shell/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  CaptureRoute: typeof CaptureRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/trends': {
      id: '/_shell/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof ShellTrendsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/teacher': {
      id: '/_shell/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof ShellTeacherRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/start': {
      id: '/_shell/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof ShellStartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions': {
      id: '/_shell/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ShellSessionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/proctor': {
      id: '/_shell/proctor'
      path: '/proctor'
      fullPath: '/proctor'
      preLoaderRoute: typeof ShellProctorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/me': {
      id: '/_shell/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof ShellMeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/management': {
      id: '/_shell/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ShellManagementRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/enrollment': {
      id: '/_shell/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof ShellEnrollmentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellEnrollmentRoute: typeof ShellEnrollmentRoute
  ShellManagementRoute: typeof ShellManagementRoute
  ShellMeRoute: typeof ShellMeRoute
  ShellProctorRoute: typeof ShellProctorRoute
  ShellSessionsRoute: typeof ShellSessionsRoute
  ShellStartRoute: typeof ShellStartRoute
  ShellTeacherRoute: typeof ShellTeacherRoute
  ShellTrendsRoute: typeof ShellTrendsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellEnrollmentRoute: ShellEnrollmentRoute,
  ShellManagementRoute: ShellManagementRoute,
  ShellMeRoute: ShellMeRoute,
  ShellProctorRoute: ShellProctorRoute,
  ShellSessionsRoute: ShellSessionsRoute,
  ShellStartRoute: ShellStartRoute,
  ShellTeacherRoute: ShellTeacherRoute,
  ShellTrendsRoute: ShellTrendsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  CaptureRoute: CaptureRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
